# Generated by Django 2.1.3 on 2018-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_charge',
            field=models.BooleanField(default=False, verbose_name='是否可以收费'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_check_arrears',
            field=models.BooleanField(default=False, verbose_name='是否可以查询欠费'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_check_charge',
            field=models.BooleanField(default=False, verbose_name='是否可以查询收费'),
        ),
    ]
