# Generated by Django 2.1.3 on 2018-12-10 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_book', models.CharField(blank=True, max_length=32, null=True, verbose_name='抄表册')),
                ('account_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='户号')),
                ('account_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='户名')),
                ('user_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='客户电话')),
                ('address', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='用电地址')),
                ('arrears', models.FloatField(blank=True, default=0.0, null=True, verbose_name='欠费金额')),
                ('arrears_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='欠费时间')),
                ('charges', models.FloatField(blank=True, default=0.0, null=True, verbose_name='收费金额')),
                ('charge_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='收费时间')),
                ('in_arrears', models.CharField(blank=True, choices=[('欠费', '欠费'), ('已收费', '已收费')], max_length=8, null=True, verbose_name='是否欠费')),
            ],
        ),
    ]
