# Generated by Django 2.1.3 on 2018-12-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_charge_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='bill_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to=settings.AUTH_USER_MODEL, verbose_name='票据管理员'),
        ),
    ]
