# Generated by Django 2.1.3 on 2018-12-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_charge_bill_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterField(
            model_name='charge',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='客户电话'),
        ),
    ]
